pipeline {
    agent any
    stages {

        stage('Lint') {
            steps {
                sh 'python3 -m pylint --output-format=parseable --fail-under=5 ./*py --msg-template="{path}:{line}: [{msg_id}({symbol}), {obj}] {msg}" | tee pylint.log || echo "pylint exited with $?"'
                echo "linting Success, Generating Report"
                recordIssues enabledForFailure: true, aggregatingResults: true, tool: pyLint(pattern: 'pylint.log')
            }
        }

        stage('Deploy') {
            steps {
                sh 'cp -r ./blog /deploy'
                sh 'cp -r ./personal_portfolio /deploy'
                sh 'cp -r ./projects /deploy'
                sh 'cp ./manage.py /deploy'                
            }
        }
               
    }
}
